<?php

namespace jobBundle\Repository\Entity;

/**
 * jobEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jobEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
