# Common
language: php
php:
  - '7.1'
env:
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
# Deployment
branches:
  only:
    - infrastructure
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: timeside2