# Common
language: php
php:
  - '7.1'
  - '5.3'
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction
# Deployment
branches:
  only:
    - infrastructure
env:
  global:
    - "FTP_USER=timeside_travisC"
    - "FTP_PASSWORD=DeployTimeside"
after_success:
    "curl --ftp-create-dirs -T * -u $FTP_USER:$FTP_PASSWORD ftp.s5.domain-ellenorzes.hu"