job:
    resource: "@jobBundle/Controller/"
    type:     annotation
    prefix:   /

time_management:
    resource: "@TimeManagementBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
